###
GET http://localhost:8080
Authorization: Basic X2VzbF9pbnRlcm5hbF93czpfZXNsX2ludGVybmFsX3dz

### bob:bobpassword
GET http://localhost:8080
Authorization: Basic Ym9iOmJvYnNwYXNzd29yZA==

### ben:$2a$10$c6bSeWPhg06xB1lvmaWNNe4NROmZiSpYhlocU/98HNr2MhIOiSt36
GET http://localhost:8080
Authorization: Basic Ym9iOmJvYnNwYXNzd29yZA==